CREATE DATABASE DB
GO
USE DB
GO

CREATE TABLE USERS
(
	ID INT IDENTITY(1,1),
	NAME NVARCHAR(50) UNIQUE,
	PASSWORD NVARCHAR(32)
)

CREATE TABLE KEY_PAIRS
(
	ID INT IDENTITY(1,1),
	OWNER_TYPE NVARCHAR(100),
	PUBLIC_KEY NVARCHAR(100),
	PRIVATE_KEY_ENCRYPTED NVARCHAR(100)

	PRIMARY KEY (ID)
)
CREATE TABLE CERTIFICATE_ROOT
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	SERIAL_NUMBER INT UNIQUE,
	SUBJECT_DN NVARCHAR(100),
	ISSUER_DN NVARCHAR(100),
	PUBLIC_KEY NVARCHAR(100),
	VALID_FROM NVARCHAR(100),
	VALID_TO NVARCHAR(100),
	SIGNATURE_ALGORITHM NVARCHAR(100),
	SIGNATURE_VALUE NVARCHAR(100)

	FOREIGN KEY (PUBLIC_KEY) REFERENCES KEY_PAIRS(PUBLIC_KEY)
)

CREATE TABLE CERTIFICATE_EXTENSIONS
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CERTIFICATE_ID INT,
	CA BOOL
	FOREIGN KEY (CERTIFICATE_ID) REFERENCES CERTIFICATE_ROOT(ID) 
)